on:
  schedule:
    - cron: '0 0 * * *'
    
  push:
     branches:
       - 'dev'
  workflow_dispatch:
     branches:
       - 'dev'

jobs:
  update-elysia:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        run: |
          apt update
          apt install -y curl
          curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | \
          sh -s -- install --no-confirm --extra-conf "trusted-users = $(whoami)" "experimental-features = nix-command flakes"
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

      - name: Get Latest Version from Source
        id: get_version
        run: |
          apt install -y jq
          LATEST_TAG=$(curl -s https://dawn.wine/api/v1/repos/elysia/elysia/releases/latest | jq -r .tag_name)
          VERSION=${LATEST_TAG#v}
          echo "Read version as v$VERSION"

      - name: Update Nix File and Hash
        run: |
          apt update && apt install -y jq curl git
          
          RAW_TAG=$(curl -s https://dawn.wine/api/v1/repos/elysia/elysia/releases/latest | jq -r .tag_name)
          CLEAN_VERSION=${RAW_TAG#v}
          
          PREFETCH_JSON=$(nix run nixpkgs#nix-prefetch-git -- --url https://dawn.wine/elysia/elysia.git --rev "$RAW_TAG")
          COMMIT_HASH=$(echo $PREFETCH_JSON | jq -r .rev)
          SHA256=$(echo $PREFETCH_JSON | jq -r .sha256)

          sed -i "s/version = \".*\";/version = \"$CLEAN_VERSION\";/" ./modules/elysia.nix
          sed -i "s/rev = \".*\";/rev = \"$COMMIT_HASH\";/" ./modules/elysia.nix
          sed -i "s/sha256 = \".*\";/sha256 = \"$SHA256\";/" ./modules/elysia.nix
 
          nix flake update

      - name: Verify Build
        run: nix build -L .

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.FORGEJO_TOKEN }}
        run: |
          apt install -y git
          NEW_VER="${{ steps.get_version.outputs.VERSION }}"
          # Define the source for the PR
          BRANCH_NAME="update-elysia-v$NEW_VER"

          git config --global user.email "bot@puppygirls.net"
          git config --global user.name "prometheus"

          # Switch to the new branch BEFORE making changes
          git fetch origin
          git checkout -b "$BRANCH_NAME" || (git checkout "$BRANCH_NAME" && git reset --hard origin/master)

          # Push the new branch to the remote
          git add .
          git commit -m "chore: bump elysia to $NEW_VER"
          git push origin "$BRANCH_NAME" --force

          # Create the PR from the new branch into master
          nix-run nixpkgs#tea -- pr create \
            --head "$BRANCH_NAME" \
            --base "master" \
            --title "Update Elysia to $NEW_VER"